config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'news' => 'static_pages#news'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post  'submitcontact' => 'static_pages#submitcontact'
  delete 'logout'  => 'sessions#destroy'
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :lists do 
    resources :items
  end
  
  resources :items
  resources :users 
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      if current_user.lists.any?
        @list = current_user.lists.first
      else
        @list = current_user.lists.build
        @list.name = "New List"
        @list.save
      end
      @item = @list.items.build
      if params[:show_all] == 'true'
        @feed_items = current_user.feed.paginate(page: params[:page])
        @num_items_todo = @feed_items.count  
        @num_items_completed = @feed_items.count - current_user.incomplete_feed.count
      else
        @feed_items = current_user.incomplete_feed.paginate(page: params[:page])
        @num_items_todo = current_user.feed.count 
        @num_items_completed = @num_items_todo - @feed_items.count
      end
    end
  end

  def submitcontact
    UserMailer.contact_admin(params[:email], params[:comment]).deliver
    flash[:success] = "Thanks for your feedback... we will review it soon."
    redirect_to root_path
  end
  
  def help
  end
  
  def about
  end

  def contact
  end 
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  Gettin' Things Done is a website to help you get things done.
</p>
<p>
    You can create as many lists of todo items as you want. Each item can have a due date, a priority, and a category.
    You can also set up reminder notifications when due dates are approaching.    
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact Us</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
        <form action="/submitcontact" method="post">

            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

            <label for="email">Your Email</label>
            <input id="email" name="email" size="30" class="form-control" type="text" />

            <label for="comment">Your Message</label>
            <textarea id="comment" name="comment" class="form-control" cols="40" rows="5">Message</textarea>

            <input class="btn btn-lg btn-primary" name="commit" type="submit" value="Send Message" />
        </form>
    </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
 This is the help section, to be filled in with helpful tips and one weird tricks.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="item_form">
        <%= render 'shared/item_form' %>
      </section>
      <section class="lists">
        <h3>Your Lists</h3>
        <% if @user.lists.any? %>
          <% @user.lists.each do |list| %>
            <div class="list_link">
              <%= link_to list.name, list %>
            </div>
          <% end %>
        <% end %>
        <div class="other">
          <%= link_to "Create List", new_list_path, :class => "btn btn-med btn-primary" %>
        </div>
      </section>
    </aside>
    <div class="col-md-8">
      <div class="item-buttons">
        <%= link_to "Show Only Incomplete Items", root_path(show_all: "false"), :class => "btn btn-sm btn-success" %>
        <%= link_to "Show All Items", root_path(show_all: "true"), :class => "btn btn-sm btn-success" %>
      </div>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>Welcome to Gettin' Things Done</h1>

  <h2>
    This is the place to get organized and get things done.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Features", about_path, class: "btn btn-lg btn-default" %>
</div>

<div class="row">
  <div class="col-md-4">
    <h3>Unlimited Lists</h3>
  </div>
    <div class="col-md-4">
    <h3>Notifications</h3>
  </div>
  <div class="col-md-4">
    <h3>Categories And Due Dates</h3>
  </div>
</div>

<% end %>

app/views/static_pages/news.html.erb
<% provide(:title, "News") %>
<h1>News</h1>
<p>
  All the news that's fit to print about this glorious website, which is nothing yet. Proudly serving society since 2015.
</p>