config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'news' => 'static_pages#news'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post  'submitcontact' => 'static_pages#submitcontact'
  delete 'logout'  => 'sessions#destroy'
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :lists do 
    resources :items
  end
  
  resources :items
  resources :users 
  

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  default_scope -> { order(created_at: :desc) }
  validates :list_id, presence: true
  validates :content, presence: true
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
  
  def index
    query = ''
    searchparam = ""
    paramarr = []
    if params[:search] && params[:search] != ''
        query += ' lower(content) LIKE ? '
        searchparam = "%#{params[:search].downcase}%"
    end

    @feed_items = Item.where(query, searchparam).paginate(page: params[:page], per_page: 10)

    @searched = query != ''
  end

  def create
    @list = List.find_by(id: item_params[:list_id])
    @item = @list.items.build(item_params)
    if @item.save
      flash[:success] = "Item created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def update
    @item = Item.find(params[:id])
    respond_to do |format|
      @item.completed = true
      if @item.save
        format.html { redirect_to @item.list.user, notice: 'Item updated.' }
        format.json { render :show, status: :ok, location: @item.list.user }
      end
    end
  end
  
  def destroy
    @item.destroy
    flash[:success] = "Item deleted."
    redirect_to request.referrer || root_url
  end

  private

    def item_params
      params.require(:item).permit(:content, :duedate, :category, :completed, :priority, :list_id)
    end
    
    def current_list
      @item = current_list.items.find_by(id: params[:id])
      redirect_to root_url if @item.nil?
    end
    
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<tr id="item-<%= item.id %>">
  <td><%= item.content %> (Created <%= time_ago_in_words(item.created_at) %> ago.)</td>
  <td><%= item.due_date %></td>
  <td><%= item.priority %></td>
  <td><%= item.category %></td>
  <td><%= link_to item.list.name, list_path(item.list) %></td>
  <td>
      
      <% if current_user?(item.list.user) && !item.completed %>
              <%= form_for(item,
               html: { method: :patch },
               remote: true) do |f| %>
                   <div><%= hidden_field_tag :item_id, item.id %></div>
                  <button type="submit" class="btn btn-sm btn-default">
                      <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                    </button>
                      
            <% end %>
        <% end %>
      <% if current_user?(item.list.user) %>
        <%= link_to [item, class: "btn btn-sm btn-warning", method: :delete,
                                         data: { confirm: "Delete this item?" }] do %>
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        <% end %>
        
      <% end %>
  </td>
</tr>

app/views/items/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/items/index.html.erb
<h1>Search Items</h1>
<div class="row">
<%= form_tag items_path, :class => "nicesearch", :method => 'get' do %>
    <div class="input-group">
      <%= text_field_tag :search, params[:search], :class => "form-control" %>
        <div class="input-group-btn">
            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
        </div>
    </div>
<% end %>
</div>
        
<div class="row">
  <div class="col-md-12">
    <% if @searched %>
    <% if @feed_items.any? %>
      <h3>Item Seach Results</h3>
    <% else %>
      <h3>No results found for that search term.</h3>
    <% end %>
    <% else %>
    <h3>Recent Items</h3>
    <% end %>
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>